/*****************************************************************************
 * Account Metadata file, all user forms and listviews are driven from here.
 Be careful while editing the file
 **************************************************************************/
const contact = {
  theme: {
    label: 'Contact',
    themeColor: '#EFE4F2',
    pluralLabel: 'Contacts',
    image: '/styles/images/workorder24.png',
    description: 'All Contacts',
    listViewActions: [
      {action: 'Delete'},
      {action: 'Edit'}
    ],
    massActions: [],
    detailActions: [],
    dbName: 'Contact',
    shareName: 'Contact__c',
  },
  permissions: {
    read: true,
    create: true,
    update: true,
    delete: true
  },
  listView: [
    {name: 'Name', label: 'Name', sorted: true, datatype: 'String', formSubType: 'text'},
    {name: 'Title', label: 'Title', sorted: true, datatype: 'String', formSubType: 'text'},
    {name: 'Phone', label: 'Phone', sorted: true, datatype: 'String', formSubType: 'text'},
    {name: 'Email', label: 'Email', sorted: true, datatype: 'String', formSubType: 'text'}
  ],
  detailView: [
    {
      name: 'Personal Information',
      cols: 2,
      fields: [
        {
          name: 'Name',
          label: 'Name',
          required: true,
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'MtgPlanner_CRM__Marital_Status__c',
          label: 'Marital Status',
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'Title',
          label: 'Title',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'Birthdate',
          label: 'Birth Date',
          required: false,
          datatype: 'Date',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'Phone',
          label: 'Phone',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MobilePhone',
          label: 'Mobile',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'HomePhone',
          label: 'Home Phone',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'Email',
          label: 'Email',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Email_2__c',
          label: 'Email 2',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {},
        {
          name: 'MtgPlanner_CRM__Co_Borrower_First_Name__c',
          label: 'First Name (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Last_Name__c',
          label: 'Last Name (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Birthdaycoborrower__c',
          label: 'Birthday (Co Borrower)',
          required: false,
          datatype: 'Date',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Mobile__c',
          label: 'Mobile (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },

        {
          name: 'MtgPlanner_CRM__Co_Borrower_Email__c',
          label: 'Email (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Email_2_Co_Borrower__c',
          label: 'Email 2 (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
      ],
    },
    {
      name: 'Address',
      cols: 2,
      fields: [
        {
          name: 'MailingStreet',
          label: 'Mailing Street',
          datatype: 'String',
          formType: 'textarea',
        },
        {
          name: 'OtherStreet',
          label: 'Other Street',
          datatype: 'String',
          formType: 'textarea',
        },
        {
          name: 'MailingCity',
          label: 'Mailing City',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'OtherCity',
          label: 'Other City',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'MailingState',
          label: 'Mailing State / Province',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'OtherState',
          label: 'Other State / Province',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'MailingPostalCode',
          label: 'Mailing Zip / Postal Code',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'OtherPostalCode',
          label: 'Other Zip / Postal Code',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'MailingCountry',
          label: 'Mailing Country',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'OtherCountry',
          label: 'Other Country',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'MtgPlanner_CRM__Mailing_Address_Type__c',
          label: 'Mailing Address Type',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'MtgPlanner_CRM__Other_Address_Type__c',
          label: 'Other Address Type',
          datatype: 'String',
          formType: 'input',
        },
      ]
    },
    {
      name: 'Additional Information',
      cols: 2,
      fields: [
        {
          name: 'MtgPlanner_CRM__SSN__c',
          label: 'SSN (Borrower)',
          datatype: 'String',
          formType: 'input',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_SSN__c',
          label: 'SSN (Co Borrower)',
          datatype: 'String',
          formType: 'input',
        },
      ],
    },
    {
      name: 'Employer / Company Information',
      cols: 2,
      fields: [
        {
          name: 'MtgPlanner_CRM__Employer_Name_Borrower__c',
          label: 'Employer Name (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          helpText: 'Your Current or Previous Employer'
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employer_Name__c',
          label: 'Employer Name (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Job_Title_Borrower__c',
          label: 'Job Title (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Title__c',
          label: 'Job Title (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Employment_Status__c',
          label: 'Employment Status (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employment_Status__c',
          label: 'Employment Status (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Years_on_Job__c',
          label: 'Years on Job (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Years_on_Job__c',
          label: 'Years on Job (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Years_in_Line_of_Work__c',
          label: 'Years in Line of Work (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Years_in_Line_of_Work__c',
          label: 'Years in Line of Work (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Employer_Address__c',
          label: 'Employer Address (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employer_Address__c',
          label: 'Employer Address (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Employer_City_State_Zip__c',
          label: 'Employer City / State / Zip (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employer_City_State_Zip__c',
          label: 'Employer City/ State/ Zip (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
      ],
    },
    {
      name: 'Hobbies and Interests',
      cols: 2,
      fields: [
        {
          name: 'Favorite_restaurant__c',
          label: 'Favorite restaurant',
          required: false,
          datatype: 'String',
          formType: 'input',
          helpText: 'Your favorite Restaurant'
        },
        {
          name: 'Favorite_charity__c',
          label: 'Favorite Charity',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Favorite_Restaurants__c',
          label: 'Favorite Restaurants',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Favorite_Movies__c',
          label: 'Favorite Movies',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Hobbies_Interests_Borrower__c',
          label: 'Hobbies / Interests (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Hobbies_Interests_Co_Borrower__c',
          label: 'Hobbies / Interests (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
        }
      ],
    },
    {
      name: 'Description',
      cols: 2,
      fields: [
        {
          name: 'Description',
          label: 'Description',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
          helpText: 'Any notes about the contact'
        }
      ],
    }
  ],
  editView: [
    {
      name: 'Personal Information',
      cols: 2,
      fields: [
        {
          name: 'FirstName',
          label: 'First Name',
          required: true,
          datatype: 'String',
          formType: 'input',
          maxLength: 40,
          helpText: 'Your First Name'
        },
        {
          name: 'MtgPlanner_CRM__Marital_Status__c',
          label: 'Marital Status',
          datatype: 'String',
          formType: 'select',
          formSubType: '',
          picklistValues: [{value: 'Married', label: 'Married'},
            {value: 'Single', label: 'Single'},
            {value: 'Separated', label: 'Separated'},
            {value: 'Divorced', label: 'Divorced'},
            {value: 'Widowed', label: 'Widowed'}]
        },
        {
          name: 'LastName',
          label: 'Last Name',
          required: true,
          datatype: 'String',
          formType: 'input',
          maxLength: 40,
          helpText: 'Your Last Name'
        },
        {
          name: 'Title',
          label: 'Title',
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength: 40,
        },
        {
          name: 'Birthdate',
          label: 'Birth Date',
          required: false,
          datatype: 'Date',
          formType: 'input',
          formSubType: 'date',
        },
        {
          name: 'Phone',
          label: 'Phone',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxlength: 40,
          formSubType: '',
        },
        {
          name: 'MobilePhone',
          label: 'Mobile',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxlength: 40,
          formSubType: '',
        },
        {
          name: 'HomePhone',
          label: 'Home Phone',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength: 40,
        },
        {
          name: 'Email',
          label: 'Email',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxlength: 80,
          formSubType: 'email',
        },
        {
          name: 'MtgPlanner_CRM__Email_2__c',
          label: 'Email 2',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: 'email',
          maxLength: 80,
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_First_Name__c',
          label: 'First Name (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Last_Name__c',
          label: 'Last Name (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Birthdaycoborrower__c',
          label: 'Birthday (Co Borrower)',
          required: false,
          datatype: 'Date',
          formType: 'input',
          formSubType: 'date',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Mobile__c',
          label: 'Mobile (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Email__c',
          label: 'Email (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
          formSubType: 'email',
        },
        {
          name: 'MtgPlanner_CRM__Email_2_Co_Borrower__c',
          label: 'Email 2 (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
          formSubType: 'email',
        },
      ],
    },
    {
      name: 'Address',
      cols: 2,
      fields: [
        {
          name: 'MailingStreet',
          label: 'Mailing Street',
          datatype: 'String',
          formType: 'textarea',
          maxLength: 255,
        },
        {
          name: 'OtherStreet',
          label: 'Other Street',
          datatype: 'String',
          formType: 'textarea',
          maxLength: 255,
        },
        {
          name: 'MailingCity',
          label: 'Mailing City',
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
        },
        {
          name: 'OtherCity',
          label: 'Other City',
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
        },
        {
          name: 'MailingState',
          label: 'Mailing State / Province',
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
        },
        {
          name: 'OtherState',
          label: 'Other State / Province',
          datatype: 'String',
          formType: 'input',
          maxLength: 80,
        },
        {
          name: 'MailingPostalCode',
          label: 'Mailing Zip / Postal Code',
          datatype: 'String',
          formType: 'input',
          maxLength: 40,
        },
        {
          name: 'OtherPostalCode',
          label: 'Other Zip / Postal Code',
          datatype: 'String',
          formType: 'input',
          maxLength: 40,
        },
        {
          name: 'MailingCountry',
          label: 'Mailing Country',
          datatype: 'String',
          formType: 'input',
          maxLength: 40,
        },
        {
          name: 'OtherCountry',
          label: 'Other Country',
          datatype: 'String',
          formType: 'input',
          maxLength: 40,
        },
        {
          name: 'MtgPlanner_CRM__Mailing_Address_Type__c',
          label: 'Mailing Address Type',
          datatype: 'String',
          formType: 'select',
          picklistValues: [{value: 'Home', label: 'Home'},
            {value: 'Business', label: 'Business'}
          ]
        },
        {
          name: 'MtgPlanner_CRM__Other_Address_Type__c',
          label: 'Other Address Type',
          datatype: 'String',
          formType: 'select',
          picklistValues: [{value: 'Home', label: 'Home'},
            {value: 'Business', label: 'Business'},
            {value: 'Rental', label: 'Rental'},
            {value: '2nd Home', label: '2nd Home'}
          ]
        },
      ]
    },

    {
      name: 'Additional Information',
      cols: 2,
      fields: [
        {
          name: 'MtgPlanner_CRM__SSN__c',
          label: 'SSN (Borrower)',
          datatype: 'String',
          formType: 'input',
          maxLength: 20
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_SSN__c',
          label: 'SSN (Co Borrower)',
          datatype: 'String',
          formType: 'input',
          maxLength: 25,
        },
      ],
    },
    {
      name: 'Employer / Company Information',
      cols: 2,
      fields: [
        {
          name: 'MtgPlanner_CRM__Employer_Name_Borrower__c',
          label: 'Employer Name (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          maxLength: 50,
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employer_Name__c',
          label: 'Employer Name (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength: 50,
        },
        {
          name: 'MtgPlanner_CRM__Job_Title_Borrower__c',
          label: 'Job Title (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength: 50,
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Title__c',
          label: 'Job Title (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength: 50,
        },
        {
          name: 'MtgPlanner_CRM__Employment_Status__c',
          label: 'Employment Status (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'select',
          formSubType: '',
          picklistValues: [{value: 'W2', label: 'W2'},
            {value: 'Self-Employed', label: 'Self-Employed'},
            {value: 'Retired', label: 'Retired'},
            {value: 'Unemployed', label: 'Unemployed'}
          ]
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employment_Status__c',
          label: 'Employment Status (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'select',
          formSubType: '',
          picklistValues: [{value: 'W2', label: 'W2'},
            {value: 'Self-Employed', label: 'Self-Employed'},
            {value: 'Retired', label: 'Retired'},
            {value: 'Unemployed', label: 'Unemployed'}
          ]
        },
        {
          name: 'MtgPlanner_CRM__Years_on_Job__c',
          label: 'Years on Job (Borrower)',
          required: false,
          datatype: 'number',
          formType: 'input',
          formSubType: 'number',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Years_on_Job__c',
          label: 'Years on Job (Co Borrower)',
          required: false,
          datatype: 'number',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Years_in_Line_of_Work__c',
          label: 'Years in Line of Work (Borrower)',
          required: false,
          datatype: 'number',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Years_in_Line_of_Work__c',
          label: 'Years in Line of Work (Co Borrower)',
          required: false,
          datatype: 'number',
          formType: 'input',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Employer_Address__c',
          label: 'Employer Address (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength:50,
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employer_Address__c',
          label: 'Employer Address (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength:50,
        },
        {
          name: 'MtgPlanner_CRM__Employer_City_State_Zip__c',
          label: 'Employer City / State / Zip (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength:50,
        },
        {
          name: 'MtgPlanner_CRM__Co_Borrower_Employer_City_State_Zip__c',
          label: 'Employer City/ State/ Zip (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength:50,
        },
      ]
    },
    {
      name: 'Hobbies and Interests',
      cols: 2,
      fields: [
        {
          name: 'Favorite_restaurant__c',
          label: 'Favorite restaurant',
          required: false,
          datatype: 'String',
          formType: 'input',
          helpText: 'Your favorite Restaurant',
          maxLength: 255,
        },
        {
          name: 'Favorite_charity__c',
          label: 'Favorite Charity',
          required: false,
          datatype: 'String',
          formType: 'input',
          formSubType: '',
          maxLength: 255
        },
        {
          name: 'MtgPlanner_CRM__Favorite_Restaurants__c',
          label: 'Favorite Restaurants',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Favorite_Movies__c',
          label: 'Favorite Movies',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
        },
        {
          name: 'MtgPlanner_CRM__Hobbies_Interests_Borrower__c',
          label: 'Hobbies / Interests (Borrower)',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
          maxLength: 1024,
        },
        {
          name: 'MtgPlanner_CRM__Hobbies_Interests_Co_Borrower__c',
          label: 'Hobbies / Interests (Co Borrower)',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
          maxLength: 1024,
        }
      ],
    },
    {
      name: 'Description',
      cols: 2,
      fields: [
        {
          name: 'Description',
          label: 'Description',
          required: false,
          datatype: 'String',
          formType: 'textarea',
          formSubType: '',
          helpText: 'Any notes or comments'
        }
      ],
    }
  ]
};

module.exports = contact;
